const express = require("express");
const auth = require("../../middlewares/auth");
const validate = require("../../middlewares/validate");
const asyncHandler = require("../../utils/asyncHandler");
const controller = require("./filtration.controller");
const validation = require("./filtration.validation");
const { errorResponse } = require("../../utils/response");
const resumeUpload = require("./resume-upload.middleware");
const interviewController = require("./interview.controller");
const statusAssistantController = require("./status-assistant.controller");
const { statusAssistantLimiter } = require("../../middlewares/rateLimiter");
const router = express.Router();

router.get("/jobs", validate(validation.listJobs), asyncHandler(controller.listJobs));
router.post("/resumes", auth("user", "recruiter"), resumeUpload.single("resume"), asyncHandler(controller.uploadResume));
router.get("/resumes/mine", auth("user", "recruiter"), asyncHandler(controller.listResumes));
router.post("/jobs", auth("user", "recruiter"), validate(validation.createJob), asyncHandler(controller.createJob));
router.get("/jobs/:id", validate(validation.id), asyncHandler(controller.getJob));
router.patch("/jobs/:id", auth("user", "recruiter"), validate(validation.updateJob), asyncHandler(controller.updateJob));
router.post("/jobs/:id/publish", auth("user", "recruiter"), validate(validation.lifecycle), asyncHandler(controller.publishJob));
router.post("/jobs/:id/schedule", auth("user", "recruiter"), validate(validation.schedule), asyncHandler(controller.scheduleJob));
router.post("/jobs/:id/pause", auth("user", "recruiter"), validate(validation.lifecycle), asyncHandler(controller.pauseJob));
router.post("/jobs/:id/resume", auth("user", "recruiter"), validate(validation.lifecycle), asyncHandler(controller.resumeJob));
router.post("/jobs/:id/fill", auth("user", "recruiter"), validate(validation.lifecycle), asyncHandler(controller.fillJob));
router.post("/jobs/:id/close", auth("user", "recruiter"), validate(validation.lifecycle), asyncHandler(controller.closeJob));
router.post("/jobs/:id/reopen", auth("user", "recruiter"), validate(validation.lifecycle), asyncHandler(controller.reopenJob));
router.post("/jobs/:id/tests", auth("user", "recruiter"), validate(validation.createTest), asyncHandler(controller.createTest));
router.get("/jobs/:id/applications", auth("user", "recruiter"), validate(validation.listJobs), asyncHandler(controller.pipeline));
router.patch("/jobs/:id/applications/bulk-review", auth("user", "recruiter"), validate(validation.bulkReview), asyncHandler(controller.bulkReview));
router.post("/jobs/:id/apply", auth("user", "recruiter"), validate(validation.apply), asyncHandler(controller.apply));
router.get("/applications/mine", auth("user", "recruiter"), asyncHandler(controller.mine));
router.post("/assistant/status", auth("user", "recruiter"), statusAssistantLimiter, validate(validation.assistant), asyncHandler(statusAssistantController.ask));
router.get("/applications/:id", auth("user", "recruiter"), validate(validation.id), asyncHandler(controller.getApplication));
router.get("/applications/:id/test", auth("user", "recruiter"), validate(validation.id), asyncHandler(controller.getTest));
router.patch("/applications/:id/test/draft", auth("user", "recruiter"), validate(validation.submit), asyncHandler(controller.saveTestDraft));
router.post("/applications/:id/test/submit", auth("user", "recruiter"), validate(validation.submit), asyncHandler(controller.submitTest));
router.get("/applications/:id/test/attempts", auth("user", "recruiter"), validate(validation.id), asyncHandler(controller.testAttempts));
router.patch("/applications/:id/test/manual-score", auth("user", "recruiter"), validate(validation.manualTaskScore), asyncHandler(controller.scoreTaskManually));
router.patch("/applications/:id/review", auth("user", "recruiter"), validate(validation.review), asyncHandler(controller.review));
router.patch("/applications/:id/withdraw", auth("user", "recruiter"), validate(validation.withdraw), asyncHandler(controller.withdraw));
router.patch("/applications/:id/management", auth("user", "recruiter"), validate(validation.management), asyncHandler(controller.updateManagement));
router.patch("/applications/:id/score-override", auth("user", "recruiter"), validate(validation.scoreOverride), asyncHandler(controller.overrideScore));
router.post("/applications/:id/interviews", auth("user", "recruiter"), validate(validation.proposeInterview), asyncHandler(interviewController.propose));
router.get("/interviews/mine", auth("user", "recruiter"), asyncHandler(interviewController.mine));
router.patch("/interviews/:id/respond", auth("user", "recruiter"), validate(validation.interviewResponse), asyncHandler(interviewController.respond));
router.patch("/interviews/:id", auth("user", "recruiter"), validate(validation.interviewUpdate), asyncHandler(interviewController.update));
router.use((error, req, res, next) => {
  if (res.headersSent) return next(error);
  return errorResponse(res, error.statusCode || 500, error.message || "Internal server error");
});
module.exports = router;
