const mongoose = require("mongoose");

const purchaseSchema = mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    type: {
      type: String,
      enum: ["music", "project", "sponsor", "project_extension"],
      default: "music",
    },
    music: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ShareMusicAsset",
      required: function () {
        return this.type === "music";
      },
    },
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Job",
    },
    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User", // For sponsorship, who receives the money
    },
    amount: {
      type: Number,
      required: true,
      min: 0,
    },
    currency: {
      type: String,
      default: "USD",
      required: true,
    },
    paymentMethod: {
      type: String,
      enum: ["wallet", "square", "stripe", "free", "paypal"],
      required: true,
    },
    squarePaymentId: {
      type: String,
      required: false,
    },
    stripePaymentIntentId: {
      type: String,
      required: false,
    },
    stripePaymentMethodId: {
      type: String,
      required: false,
    },
    billingAddress: {
      line1: String,
      city: String,
      state: String,
      postalCode: String,
      country: String,
    },
    savePaymentInfo: {
      type: Boolean,
      default: false,
    },
    licenseType: {
      type: String,
      required: function () {
        return this.type === "music";
      },
    },
    licenseId: {
      type: String,
      required: false,
    },
    status: {
      type: String,
      enum: ["pending", "completed", "failed", "refunded"],
      default: "pending",
    },
    transactionId: {
      type: String,
      unique: true,
      required: false, // Will be generated by pre-save hook
    },
    downloadCount: {
      type: Number,
      default: 0,
    },
    lastDownloadedAt: {
      type: Date,
    },
    metadata: {
      userAgent: String,
      ipAddress: String,
      notes: String,
    },
  },
  {
    timestamps: true,
  },
);

// Add indexes for better query performance
purchaseSchema.index({ user: 1, createdAt: -1 });
purchaseSchema.index({ music: 1 });
purchaseSchema.index({ projectId: 1 });
purchaseSchema.index({ transactionId: 1 });
purchaseSchema.index({ squarePaymentId: 1 });
purchaseSchema.index({ stripePaymentIntentId: 1 });
purchaseSchema.index({ status: 1 });

// Generate unique transaction ID before saving
purchaseSchema.pre("save", function (next) {
  if (this.isNew && !this.transactionId) {
    this.transactionId = `TXN_${Date.now()}_${Math.random()
      .toString(36)
      .substr(2, 9)}`;
  }
  next();
});

// Middleware to handle balance updates when purchase is completed
purchaseSchema.post("save", async function (doc) {
  // Only process if status changed to 'completed'
  if (this.isModified("status") && doc.status === "completed") {
    try {
      const balanceHelper = require("../utils/balanceHelper");

      // Add balance to the music asset owner (seller)
      await balanceHelper.addPurchaseBalance(
        doc.music,
        doc._id,
        doc.amount,
        doc.licenseType,
      );

      console.log(`✅ Balance added to music owner for purchase ${doc._id}`);
    } catch (error) {
      console.error("❌ Error adding balance for purchase:", error);
    }
  }
});

// Middleware to handle balance updates when new purchase is created
purchaseSchema.post("save", async function (doc) {
  // Only process for new completed purchases (immediate payment)
  if (
    this.isNew &&
    doc.status === "completed" &&
    doc.paymentMethod !== "wallet"
  ) {
    try {
      const balanceHelper = require("../utils/balanceHelper");

      // Get music title for transaction description if type is music
      const ShareMusicAsset = require("./shareMusicAsset.model");
      let itemTitle = "Item";

      if (doc.type === "music" && doc.music) {
        const musicAsset = await ShareMusicAsset.findById(doc.music);
        itemTitle = musicAsset ? musicAsset.songName : "Music Asset";
      } else if (doc.type === "project") {
        itemTitle = "Project Creation Fee";
      } else if (doc.type === "sponsor") {
        itemTitle = "Sponsorship";
      }

      // Deduct balance if payment method is wallet
      if (doc.paymentMethod === "wallet") {
        await balanceHelper.deductPurchaseBalance(
          doc.user,
          doc.amount,
          doc._id,
          itemTitle,
        );

        console.log(
          `✅ Balance deducted from user ${doc.user} for purchase ${doc._id}`,
        );
      }
    } catch (error) {
      console.error("❌ Error processing purchase balance:", error);
    }
  }
});

/**
 * @typedef Purchase
 */
const Purchase = mongoose.model("Purchase", purchaseSchema);

module.exports = Purchase;
