const mongoose = require("mongoose");

const purchaseSchema = mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    type: {
      type: String,
      enum: ["project", "sponsor", "project_extension"],
      default: "project",
    },
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Job",
    },
    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User", // For sponsorship, who receives the money
    },
    amount: {
      type: Number,
      required: true,
      min: 0,
    },
    currency: {
      type: String,
      default: "USD",
      required: true,
    },
    paymentMethod: {
      type: String,
      enum: ["wallet", "square", "stripe", "free", "paypal"],
      required: true,
    },
    squarePaymentId: {
      type: String,
      required: false,
    },
    stripePaymentIntentId: {
      type: String,
      required: false,
    },
    stripePaymentMethodId: {
      type: String,
      required: false,
    },
    billingAddress: {
      line1: String,
      city: String,
      state: String,
      postalCode: String,
      country: String,
    },
    savePaymentInfo: {
      type: Boolean,
      default: false,
    },
    status: {
      type: String,
      enum: ["pending", "completed", "failed", "refunded"],
      default: "pending",
    },
    transactionId: {
      type: String,
      unique: true,
      required: false, // Will be generated by pre-save hook
    },
    metadata: {
      userAgent: String,
      ipAddress: String,
      notes: String,
    },
  },
  {
    timestamps: true,
  },
);

// Add indexes for better query performance
purchaseSchema.index({ user: 1, createdAt: -1 });
purchaseSchema.index({ projectId: 1 });
purchaseSchema.index({ transactionId: 1 });
purchaseSchema.index({ squarePaymentId: 1 });
purchaseSchema.index({ stripePaymentIntentId: 1 });
purchaseSchema.index({ status: 1 });

// Generate unique transaction ID before saving
purchaseSchema.pre("save", function (next) {
  if (this.isNew && !this.transactionId) {
    this.transactionId = `TXN_${Date.now()}_${Math.random()
      .toString(36)
      .substr(2, 9)}`;
  }
  next();
});


/**
 * @typedef Purchase
 */
const Purchase = mongoose.model("Purchase", purchaseSchema);

module.exports = Purchase;
